name: management_invoices
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fluent_ui: ^4.11.2
  window_manager: ^0.4.3
  provider: ^6.1.2
  dio: ^5.8.0+1
  file_picker: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: MSYH
      fonts:
        - asset: assets/fonts/MSYH.TTC
          weight: 400
        - asset: assets/fonts/MSYHL.TTC
          weight: 300
        - asset: assets/fonts/MSYHBD.TTC
          weight: 700

  assets:
    - assets/images/
