name: management_invoices
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fluent_ui: ^4.11.2
  window_manager: ^0.4.3
  provider: ^6.1.2
  dio: ^5.8.0+1
  file_picker: ^9.0.2
  equatable: ^2.0.7
  syncfusion_flutter_datagrid: ^29.1.33
  shared_preferences: ^2.5.2
  decimal: ^3.0.2
  freezed_annotation: ^3.0.0
  path: ^1.9.1
  collapsible_sidebar: ^2.0.7
  sidebarx: ^0.17.1
  syncfusion_flutter_charts: ^29.1.33
  intl: ^0.19.0
  collection: ^1.19.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  msix: ^3.16.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/touxiang.jpg
    - assets/images/icon.jpg
  fonts:
    - family: MSYH
      fonts:
        - asset: assets/fonts/MSYH.TTC
          weight: 400
        - asset: assets/fonts/MSYHL.TTC
          weight: 300
        - asset: assets/fonts/MSYHBD.TTC
          weight: 700


msix_config:
  certificate_path: C:/Users/justinc/Documents/CERTIFICATE.pfx         # PFX证书文件路径
  certificate_password: SJCsjc0315       # 证书密码（创建pfx时设置的导出密码）
  logo_path: assets/images/icon.png       # 应用图标（建议至少256x256）
  msix_version: 1.0.0.0